### ISSUE TITLE
Suddenly slow and lagging simulation in Unity with only 1.9 FPS update rate

### ISSUE THREAD

**Issue by anevagale** [Gemini-team/Gemini#42]
The simulation speed suddenly dropped down from approx. 26 FPS to 1.9 FPS using Unity `2019.4.21f1`.
Reading forums I found out that many people have had a similar issue.
What solved this problem for me was logging out and back in the Unity account.

**Comment by Skarsh** [comment]
> 
> 
> The simulation speed suddenly dropped down from approx. 26 FPS to 1.9 FPS using Unity 2019.4.21f1.
> Reading forums I found out that many people have had a similar issue.
> What solved this problem for me was logging out and back in the Unity account.

Thank you for sharing this information, I have not tested Gemini at `2019.4.21f1` so I have not had this problem myself. Do you know if this is a problem in 2019.4.22f1 aswell?

**Comment by anevagale** [comment]
> > The simulation speed suddenly dropped down from approx. 26 FPS to 1.9 FPS using Unity 2019.4.21f1.
> > Reading forums I found out that many people have had a similar issue.
> > What solved this problem for me was logging out and back in the Unity account.
> 
> Thank you for sharing this information, I have not tested Gemini at `2019.4.21f1` so I have not had this problem myself. Do you know if this is a problem in 2019.4.22f1 aswell?

Not sure. People have had same problem since one of versions from 2017.
